// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkWw2Y2vf4-6viifMz50Ctg1jh-hej9M',
    appId: '1:670650028874:web:f5975875aae456823267b3',
    messagingSenderId: '670650028874',
    projectId: 'enpit-weeee',
    authDomain: 'enpit-weeee.firebaseapp.com',
    storageBucket: 'enpit-weeee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWqzVblGUubRLjeFEldxhYWwlUhJxGT0',
    appId: '1:670650028874:android:48819203081cd2df3267b3',
    messagingSenderId: '670650028874',
    projectId: 'enpit-weeee',
    storageBucket: 'enpit-weeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5t5mrYm06mUMrtMN5CBRFi_mo6vcTs-M',
    appId: '1:670650028874:ios:31f06b627285a6a03267b3',
    messagingSenderId: '670650028874',
    projectId: 'enpit-weeee',
    storageBucket: 'enpit-weeee.appspot.com',
    iosClientId: '670650028874-tvh7gpfbip11bppc6oeditkspmh4ggau.apps.googleusercontent.com',
    iosBundleId: 'com.example.enpitWeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5t5mrYm06mUMrtMN5CBRFi_mo6vcTs-M',
    appId: '1:670650028874:ios:31f06b627285a6a03267b3',
    messagingSenderId: '670650028874',
    projectId: 'enpit-weeee',
    storageBucket: 'enpit-weeee.appspot.com',
    iosClientId: '670650028874-tvh7gpfbip11bppc6oeditkspmh4ggau.apps.googleusercontent.com',
    iosBundleId: 'com.example.enpitWeee',
  );
}
