// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFcxIILDcZQ03Y5rVWaTgDmjY6icQh40',
    appId: '1:631066516008:web:d89bed81b09df8f8b4731d',
    messagingSenderId: '631066516008',
    projectId: 'empit-weee',
    authDomain: 'empit-weee.firebaseapp.com',
    storageBucket: 'empit-weee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigwooTGcqn9bFKLQCCq8R8ymUDztnBOU',
    appId: '1:631066516008:android:c3a993e6d8bd9496b4731d',
    messagingSenderId: '631066516008',
    projectId: 'empit-weee',
    storageBucket: 'empit-weee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShfj6BsjxUo1OEf2aHxnDhgWmSy6HMy4',
    appId: '1:631066516008:ios:ad4eb9f0d00a2b4eb4731d',
    messagingSenderId: '631066516008',
    projectId: 'empit-weee',
    storageBucket: 'empit-weee.appspot.com',
    iosClientId: '631066516008-j3166pthuvsjm880ce262shv6qk5c7e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.enpitWeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShfj6BsjxUo1OEf2aHxnDhgWmSy6HMy4',
    appId: '1:631066516008:ios:ad4eb9f0d00a2b4eb4731d',
    messagingSenderId: '631066516008',
    projectId: 'empit-weee',
    storageBucket: 'empit-weee.appspot.com',
    iosClientId: '631066516008-j3166pthuvsjm880ce262shv6qk5c7e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.enpitWeee',
  );
}
